apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: nats
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: pangarabbit
  source:
    repoURL: "https://nats-io.github.io/k8s/helm/charts/"
    targetRevision: 1.2.0
    chart: nats
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nats
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
